#!/usr/bin/with-contenv bash
# shellcheck shell=bash

echo '
╔════════════════════════════════════════════════════╗
╠════════════════════════════════════════════════════╣
║                                                    ║
║             This image is deprecated.              ║
║      We will not offer support for this image      ║
║            and it will not be updated.             ║
║                                                    ║
╠════════════════════════════════════════════════════╣
╚════════════════════════════════════════════════════╝

The upstream project has no plans to fix GPU support

══════════════════════════════════════════════════════'
